title: Расчеты СИЗОД ГДЗС | Android-приложение
email: eevcode@gmail.com
description: Мобильное приложение для расчета расхода воздуха СИЗОД на посту безопасности ГДЗС.
baseurl: ""
url: "https://gdzs.eecode.ru"
google_play_url: "https://play.google.com/store"

plugins:
  # - jekyll-feed

sass:
  sass_dir:           _sass
  style:              compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - gulpfile.mjs
  - .babelrc
  - .gitignore
  - CNAME
  - package.json
  - yarn.lock
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
